entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  http:
    acme:
      email: "tombury59@hotmail.com" # <--- remplace par ton email
      storage: "/acme.json"
      httpChallenge:
        entryPoint: "web"
