import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
import ServiceWorkerRegister from "./ServiceWorkerRegister";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="fr">
        <head>
            <link rel="manifest" href="/manifest.json" />
            <link rel="icon" href="/images/icons/Logo-192x192.png" sizes="192x192" type="image/png" />
            <meta name="theme-color" content="#0070f3" />
        </head>
        <body>
        <ServiceWorkerRegister />
        {children}
        </body>
        </html>
    );
}
